import type { FeedSource } from "./types";

/** Curated free RSS & YouTube channel feeds (no API key required). */
export const DEFAULT_FEEDS: FeedSource[] = [
  {
    id: "bbc-world",
    name: "BBC World",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    type: "rss",
    category: "World",
    region: "Global",
    country: "United Kingdom",
  },
  {
    id: "bbc-uk",
    name: "BBC UK",
    url: "https://feeds.bbci.co.uk/news/england/rss.xml",
    type: "rss",
    category: "World",
    region: "Western",
    country: "United Kingdom",
  },
  {
    id: "bbc-tech",
    name: "BBC Technology",
    url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
    type: "rss",
    category: "Technology",
    region: "Global",
    country: "United Kingdom",
  },
  {
    id: "npr-news",
    name: "NPR News",
    url: "https://feeds.npr.org/1001/rss.xml",
    type: "rss",
    category: "World",
    region: "Americas",
    country: "United States",
  },
  {
    id: "nyt-world",
    name: "NY Times World",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    type: "rss",
    category: "World",
    region: "Americas",
    country: "United States",
  },
  {
    id: "guardian-world",
    name: "The Guardian",
    url: "https://www.theguardian.com/world/rss",
    type: "blog",
    category: "World",
    region: "Western",
    country: "United Kingdom",
  },
  {
    id: "guardian-us",
    name: "Guardian US",
    url: "https://www.theguardian.com/us-news/rss",
    type: "blog",
    category: "World",
    region: "Americas",
    country: "United States",
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    type: "blog",
    category: "Technology",
    region: "Global",
    country: "United States",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    type: "rss",
    category: "World",
    region: "Middle East",
    country: "Qatar",
  },
  {
    id: "france24",
    name: "France 24",
    url: "https://www.france24.com/en/rss",
    type: "rss",
    category: "World",
    region: "Western",
    country: "France",
  },
  {
    id: "dw-news",
    name: "DW News",
    url: "https://rss.dw.com/rdf/rss-en-world",
    type: "rss",
    category: "World",
    region: "Western",
    country: "Germany",
  },
  {
    id: "youtube-bbc",
    name: "BBC News (YouTube)",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC16niRr50-MSbwiVs3hHaUg",
    type: "youtube",
    category: "Live",
    region: "Global",
    country: "United Kingdom",
  },
  {
    id: "youtube-cnn",
    name: "CNN (YouTube)",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCupvZG-5ko_eiXAupbDfxWw",
    type: "youtube",
    category: "Live",
    region: "Americas",
    country: "United States",
  },
  {
    id: "youtube-reuters",
    name: "Reuters (YouTube)",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UChqUXGYxI1SftkCTDDoNmeA",
    type: "youtube",
    category: "Business",
    region: "Global",
    country: "United Kingdom",
  },
  {
    id: "youtube-verge",
    name: "The Verge (YouTube)",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCddiUEpeqJcYeBxX1IVBKvQ",
    type: "youtube",
    category: "Technology",
    region: "Global",
    country: "United States",
  },
  {
    id: "youtube-france24",
    name: "France 24 (YouTube)",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQfwfsi6V0k79QS0yisK2qA",
    type: "youtube",
    category: "Live",
    region: "Western",
    country: "France",
  },
];
